# Generated by Django 6.0.2 on 2026-03-06 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouel_courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='ouel_courses.section'),
        ),
        migrations.AlterField(
            model_name='theorylesson',
            name='minimum_time',
            field=models.IntegerField(help_text='Thời gian tối đa hoàn thành bài học'),
        ),
    ]
