# Generated by Django 6.0.2 on 2026-03-07 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouel_courses', '0002_alter_reply_options_remove_lesson_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attachment',
            field=models.FileField(default='', max_length=255, upload_to='lessons/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'zip', 'mp4', 'mp3', 'png', 'jpg'])]),
        ),
    ]
