# Generated by Django 6.0.1 on 2026-01-26 07:42

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("time", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-updated_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TagExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TagLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TagPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "type_part",
                    models.CharField(
                        choices=[
                            ("complete_sentence", "Complete Sentence"),
                            ("complete_paragraph", "Complete Paragraph"),
                            ("reading_comprehension", "Reading Comprehension"),
                        ],
                        default="reading_comprehension",
                        max_length=100,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ouel_reading_app.exam",
                    ),
                ),
                ("tag", models.ManyToManyField(blank=True, to="ouel_reading_app.tag")),
                (
                    "tag_parts",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ouel_reading_app.tagpart",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("user_id", models.IntegerField()),
                ("total_answers", models.IntegerField()),
                ("correct_answers", models.IntegerField()),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("time", models.IntegerField()),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ouel_reading_app.part",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("question_text", models.CharField(max_length=225)),
                ("option_a", models.CharField(max_length=225)),
                ("option_b", models.CharField(max_length=225)),
                ("option_c", models.CharField(max_length=225)),
                ("option_d", models.CharField(max_length=225)),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[
                            ("A", "Lựa chọn A"),
                            ("B", "Lựa chọn B"),
                            ("C", "Lựa chọn C"),
                            ("D", "Lựa chọn D"),
                        ],
                        max_length=1,
                    ),
                ),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ouel_reading_app.part",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_date"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="tag_exams",
            field=models.ManyToManyField(blank=True, to="ouel_reading_app.tagexam"),
        ),
        migrations.AddField(
            model_name="exam",
            name="tag_levels",
            field=models.ManyToManyField(blank=True, to="ouel_reading_app.taglevel"),
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("user_answer", models.CharField(max_length=1, null=True)),
                ("is_correct", models.BooleanField()),
                (
                    "part_history",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="ouel_reading_app.parthistory",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ouel_reading_app.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_date"],
                "abstract": False,
            },
        ),
    ]
