# Generated by Django 5.2.8 on 2025-11-27 02:58

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OUELApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(max_length=100)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('prompt_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('prompt_role', models.CharField(max_length=100)),
                ('prompt_instructions', models.TextField(max_length=1000)),
                ('prompt_constraints', models.TextField(max_length=300)),
                ('prompt_output', models.TextField(max_length=500)),
                ('ouelapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeminiAPI.ouelapp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
