# Generated by Django 5.2.8 on 2025-11-27 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeminiAPI', '0002_alter_prompt_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='ouelapp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_config', to='GeminiAPI.ouelapp'),
        ),
    ]
