# Generated by Django 5.2.8 on 2025-11-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeminiAPI', '0003_alter_prompt_ouelapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='is_active',
        ),
    ]
