# Generated by Django 5.2.8 on 2025-11-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeminiAPI', '0004_remove_prompt_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='prompt_instructions',
            field=models.TextField(max_length=3000),
        ),
    ]
