# Generated by Django 5.2.8 on 2025-11-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeminiAPI', '0005_alter_prompt_prompt_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='prompt_constraints',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_output',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_role',
            field=models.CharField(max_length=300),
        ),
    ]
