# Generated by Django 6.0.1 on 2026-02-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouel_cources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
