# Generated by Django 5.2.8 on 2025-11-28 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('question_text', models.CharField(max_length=225)),
                ('option_a', models.CharField(max_length=225)),
                ('option_b', models.CharField(max_length=225)),
                ('option_c', models.CharField(max_length=225)),
                ('option_d', models.CharField(max_length=225)),
                ('correct_answer', models.CharField(choices=[('A', 'Lựa chọn A'), ('B', 'Lựa chọn B'), ('C', 'Lựa chọn C'), ('D', 'Lựa chọn D')], max_length=1)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.passage')),
            ],
            options={
                'unique_together': {('question_text', 'passage')},
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('score_percentage', models.FloatField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.passage')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_answer', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField()),
                ('attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuizApp.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.question')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
