# Generated by Django 6.0.1 on 2026-02-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ouel_reading_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parthistory",
            options={"verbose_name": "Part historie"},
        ),
    ]
