# Generated by Django 6.0.1 on 2026-01-26 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ouel_oauth", "0002_hobby_loginhistory_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loginhistory",
            options={"verbose_name": "Login historie"},
        ),
    ]
