# Generated by Django 6.0.1 on 2026-01-25 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ouel_oauth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ouel_oauth_login_history",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("biography", models.CharField(default="", max_length=255)),
                ("about", models.TextField(default="", max_length=2600)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("a1", "Cấp độ A1"),
                            ("a2", "Cấp độ A2"),
                            ("b1", "Cấp độ B1"),
                            ("b2", "Cấp độ B2"),
                            ("c1", "Cấp độ C1"),
                            ("c2", "Cấp độ C2"),
                        ],
                        default="a1",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("hobbies", models.ManyToManyField(blank=True, to="ouel_oauth.hobby")),
            ],
        ),
    ]
