# Generated by Django 6.0.2 on 2026-02-12 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ouel_oauth", "0003_alter_loginhistory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorProfile",
            fields=[
                ("biography", models.CharField(blank=True, default="", max_length=255)),
                ("about", models.TextField(blank=True, default="", max_length=2600)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("title", models.CharField(default="Instructor", max_length=255)),
                ("experience", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Instructor profile",
            },
        ),
        migrations.AlterModelOptions(
            name="loginhistory",
            options={"verbose_name": "Login log"},
        ),
        migrations.AddField(
            model_name="loginhistory",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loginhistory",
            name="user_agent",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Học viên"),
                    ("instructor", "Giảng viên"),
                    ("admin", "Quản trị viên"),
                ],
                default="student",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_provider",
            field=models.CharField(
                choices=[("google", "Google"), ("email", "Email/Password")],
                default="email",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                ("biography", models.CharField(blank=True, default="", max_length=255)),
                ("about", models.TextField(blank=True, default="", max_length=2600)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("a1", "Cấp độ A1"),
                            ("a2", "Cấp độ A2"),
                            ("b1", "Cấp độ B1"),
                            ("b2", "Cấp độ B2"),
                            ("c1", "Cấp độ C1"),
                            ("c2", "Cấp độ C2"),
                        ],
                        default="a1",
                        max_length=255,
                    ),
                ),
                ("goal", models.TextField(blank=True, null=True)),
                (
                    "interests",
                    models.ManyToManyField(blank=True, to="ouel_oauth.hobby"),
                ),
            ],
            options={
                "verbose_name": "Student profile",
            },
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ouel_oauth_user_follow",
            },
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.AddIndex(
            model_name="userfollow",
            index=models.Index(
                fields=["follower", "-created_at"],
                name="ouel_oauth__followe_45aa3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userfollow",
            index=models.Index(
                fields=["followed", "-created_at"],
                name="ouel_oauth__followe_952fdd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="userfollow",
            constraint=models.UniqueConstraint(
                fields=("follower", "followed"), name="unique_user_follow"
            ),
        ),
        migrations.AddConstraint(
            model_name="userfollow",
            constraint=models.CheckConstraint(
                condition=models.Q(("follower", models.F("followed")), _negated=True),
                name="prevent_self_follow",
            ),
        ),
    ]
