# Generated by Django 6.0.2 on 2026-03-06 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouel_oauth', '0005_data_migrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name': 'Hobbie'},
        ),
        migrations.AlterModelOptions(
            name='userfollow',
            options={'verbose_name': 'User follower'},
        ),
    ]
