version: "3.9"
services:
  db:
    image: mysql:8
    restart: always
    env_file:
      - .env

    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 10
  backend:
    build:
      context: ./backend
      args:
        - REQUIREMENT_FILE=${CONFIG_MODE}
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
          condition: service_healthy
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  mysql_data: