# Generated by Django 6.0.1 on 2026-01-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ouel_gemini", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promptlog",
            old_name="token_used",
            new_name="token",
        ),
        migrations.RemoveField(
            model_name="promptlog",
            name="updated_date",
        ),
        migrations.AddField(
            model_name="promptlog",
            name="status",
            field=models.IntegerField(default=200),
        ),
    ]
