# Generated by Django 6.0.1 on 2026-01-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ouel_gemini", "0002_rename_token_used_promptlog_token_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aimodel",
            options={"verbose_name": "Model"},
        ),
    ]
