# Generated by Django 6.0.1 on 2026-01-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ouel_gemini", "0003_alter_aimodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="name",
            field=models.CharField(
                choices=[
                    ("gemini-2.5-flash-lite", "Version2 5 Lite"),
                    ("gemini-2.5-flash", "Version2 5"),
                    ("gemini-3-flash-preview", "Version3"),
                ],
                default="gemini-2.5-flash",
                max_length=100,
            ),
        ),
    ]
