# Generated by Django 6.0.1
from django.db import migrations

def create_grammar_prompt(apps, schema_editor):
    AIModel = apps.get_model('ouel_gemini', 'AIModel')
    Prompt = apps.get_model('ouel_gemini', 'Prompt')

    ai_model, created = AIModel.objects.get_or_create(
        name='gemini-2.5-flash',
        defaults={
            'provider': 'gemini',
            'active': True
        }
    )

    few_shot_examples = """
Examples (Few-shot Learning):

Example 1:
Input: "I has finish my homework yesterday."
Output:
{
  "id": "eval_001",
  "original": "I has finish my homework yesterday.",
  "error": null,

  "correctness": {
    "result": "I finished my homework yesterday.",
    "explanation": "Sai thì quá khứ và chia động từ.",
    "issues": [
      {
        "id": "g1",
        "message": "Sai chia động từ và thì quá khứ.",
        "original": "has finish",
        "fix": "finished",
        "start": 2,
        "end": 12
      }
    ]
  },

  "clarity": {
    "result": "I finished my homework yesterday.",
    "explanation": "Câu rõ ràng, dễ hiểu.",
    "issues": []
  },

  "engagement": {
    "result": "I was happy after finishing my homework yesterday.",
    "explanation": "Câu còn đơn giản, chưa tạo cảm xúc.",
    "issues": [
      {
        "id": "e1",
        "message": "Có thể thêm cảm xúc để câu sinh động hơn.",
        "original": "I finished my homework yesterday.",
        "fix": "I was happy after finishing my homework yesterday.",
        "start": 0,
        "end": 36
      }
    ]
  },

  "delivery": {
    "result": "I finished my homework yesterday.",
    "explanation": "Giọng văn trung tính, phù hợp.",
    "issues": []
  }
}

Example 2:
Input: "I enjoy learning English because it helps me communicate with people around the world."
Output:
{
  "id": "eval_002",
  "error": null,

  "correctness": {
    "result": "I enjoy learning English because it helps me communicate with people around the world.",
    "explanation": "none",
    "issues": []
  },

  "clarity": {
    "result": "I enjoy learning English because it helps me communicate with people around the world.",
    "explanation": "none",
    "issues": []
  },

  "engagement": {
    "result": "I enjoy learning English because it helps me communicate with people around the world.",
    "explanation": "none",
    "issues": []
  },

  "delivery": {
    "result": "I enjoy learning English because it helps me communicate with people around the world.",
    "explanation": "none",
    "issues": []
  }
}

Example 3:
Input: "Xin chào bạn"
Output:
{
  "id": "eval_003",
  "original": "Xin chào bạn",
  "error": "Nội dung không phải tiếng Anh nên không thể đánh giá.",

  "correctness": {
    "result": "Xin chào bạn",
    "explanation": "none",
    "issues": []
  },

  "clarity": {
    "result": "Xin chào bạn",
    "explanation": "none",
    "issues": []
  },

  "engagement": {
    "result": "Xin chào bạn",
    "explanation": "none",
    "issues": []
  },

  "delivery": {
    "result": "Xin chào bạn",
    "explanation": "none",
    "issues": []
  }
}
"""
    instruction_content = f"""You are an English writing evaluation assistant.
Your task is to analyze the user's text and return feedback.
You MUST respond ONLY with valid JSON.
Do NOT include markdown (like ```json).
Do NOT include explanations outside JSON.

{few_shot_examples}
"""
    context_content = """You must return a JSON object with the following top-level fields:
- "id": a unique string identifier for this evaluation
- "error": null or a Vietnamese error message if the text cannot be evaluated
- "correctness"
- "clarity"
- "engagement"
- "delivery"
For each category (correctness, clarity, engagement, delivery), return an object with:
- "result":
    • A corrected or improved FULL English sentence (or short paragraph)
    • Keep the original meaning
    • If no improvement is needed, return the original sentence

- "explanation":
    • Written in Vietnamese
    • Brief explanation or feedback
    • If no issue exists, set this field to "none"

- "issues": an array of specific issues
    • If there are no issues, return an empty array []

Each issue object MUST have:
- "id": unique string identifier
- "message": Vietnamese description of the issue
- "original": the original input text (unchanged)
- "fix": corrected English text for that specific part
- "start": starting index of the issue in the original text (integer)
- "end": ending index of the issue in the original text (integer)

IMPORTANT RULES:
- Respond in Vietnamese for all explanations and messages
- Respond in English ONLY for result and fix
- Do NOT explain inside result or fix
- Do NOT rewrite the entire text unless necessary
- Always return all four categories
- If the input is NOT English, set "error" and still return all categories with empty issues

OUTPUT FORMAT:
{
  "id": "string",
  "original": "string",
  "error": null | "string",

  "correctness": {
    "result": "string",
    "explanation": "string | 'none'",
    "issues": [
      {
        "id": "string",
        "message": "string",
        "original": "string",
        "fix": "string",
        "start": number,
        "end": number
      }
    ]
  },

  "clarity": { same structure },
  "engagement": { same structure },
  "delivery": { same structure }
}
"""

    Prompt.objects.create(
        name="check-grammar",
        version=1,
        instruction=instruction_content,
        context=context_content,
        settings={"temperature": 0.4, "topK": 40}, 
        ai_model=ai_model
    )

    highlight_instruction_content = f"""
    You are an AI powered answer suggestion system. Your task is to find the consecutive and complete text range in the provided Passage that suggests the answer to the Question.

    Your task:
    1. Identify the most accurate consecutive text range that suggests the correct answer in the passage.
    2. Calculate the start and end index based on the characters of the extracted text compared to the provided Passage above.
    3. Output only one JSON object.

    Rule:
    - Do not add, delete or change any characters in "answerText". The text in "answerText" must exactly match the Paragraph section and have at least 2 sentences.
    - Do not return additional text outside of JSON.
    """

    highlight_context_content = """
        The JSON format must be strictly followed:
    {{
        "answerText": "exact suggested text range copied from the Passage",
        "startIndex": number,
        "endIndex": number
    }}
    """

    Prompt.objects.create(
        name="highlight-passage",
        version=1,
        instruction=highlight_instruction_content,
        context=highlight_context_content,
        settings={"temperature": 0.4, "topK": 30}, 
        ai_model=ai_model
    )

def remove_grammar_prompt(apps, schema_editor):
    Prompt = apps.get_model('ouel_gemini', 'Prompt')
    Prompt.objects.filter(name="Writing Grammar Checker", version=1).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("ouel_gemini", "0004_alter_aimodel_name"),
    ]

    operations = [
        migrations.RunPython(create_grammar_prompt, remove_grammar_prompt),
    ]